### ISSUE TITLE
Soporte USB

### ISSUE THREAD

**Issue by dansanti** [TransbankDevelopers/transbank-pos-sdk-python#13]
Hola, podrían por favor agregar la estructura para agregar usb_manager, ya que vi tienen soporte para utilizarlo en la clase POS  pero solo en modo serial, he hecho algunas pruebas con usb siguiendo los lineamentos seriales pero la estructura no permite seleccionar si es serial o usb

**Comment by Matiasnickolas** [comment]
Hola! @dansanti, el que se comunique por serial o USB debe ser definido directamente en el POS, para el SDK esto es transparente y puede trabajar con ambos tipos, no es necesario indicarle con que tipo se comunica.
