### ISSUE TITLE
Indicación confusa en error ticket

### ISSUE THREAD

**Issue by dansanti** [TransbankDevelopers/transbank-pos-sdk-python#19]
Hola!
Según el error debe ser mayor que 6, pero la validación es menor que 6, ( el error aparece porque len(ticket) > 6)

https://github.com/TransbankDevelopers/transbank-pos-sdk-python/blob/10cff58684f215510067631c0c53587711cdce9f/transbank/POS/POSIntegrado.py#L78

**Comment by Matiasnickolas** [comment]
Hola! Eso indica que debe ser hasta 6. De todos modos realizamos un cambio en el mensaje para que sea más descriptivo.
#20
